Do not move windows .exes
Signed-off-by: Richard Bonhomme <tincanteksup@gmail.com>

diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -1962,18 +1962,20 @@ move_easyrsa2_programs ()
 	done
 
 	# Hard coded versions
-	for i in 	awk.exe cat.exe cp.exe date.exe diff.exe grep.exe libcrypto-1_1.dll libssl-1_1.dll \
-			ls.exe md5sum.exe mkdir.exe mktemp.exe mv.exe openssl.exe printf.exe rm.exe \
-			sed.exe which.exe; do
-		if [ -f "$EASYRSA/$i" ]
-		then
-			cp "$EASYRSA/$i" "$EASYRSA_SAFE_PKI" \
-				|| fail_upgrade "Failed to copy $EASYRSA/$i $EASYRSA_SAFE_PKI"
-			[ "$EASYRSA_UPGRADE_TYPE" = "REAL" ] && rm  -f "$EASYRSA/$i"
-		else
-			printf "%s\n" "  File does not exist, ignoring: $i"
-		fi
-	done
+	# These should not be in this directory anyway, so maybe not bother
+	#for i in 	awk.exe cat.exe cp.exe date.exe diff.exe grep.exe libcrypto-1_1.dll libssl-1_1.dll \
+	#		ls.exe md5sum.exe mkdir.exe mktemp.exe mv.exe openssl.exe printf.exe rm.exe \
+	#		sed.exe which.exe; do
+	#	if [ -f "$EASYRSA/$i" ]
+	#	then
+	#		cp "$EASYRSA/$i" "$EASYRSA_SAFE_PKI" \
+	#			|| fail_upgrade "Failed to copy $EASYRSA/$i $EASYRSA_SAFE_PKI"
+	#		# Cannot remove these exes until windows has finished with them
+	#		#[ "$EASYRSA_UPGRADE_TYPE" = "REAL" ] && rm  -f "$EASYRSA/$i"
+	#	else
+	#		printf "%s\n" "  File does not exist, ignoring: $i"
+	#	fi
+	#done
 
 	printf "%s\n" "  OK"
 	# These files are not removed on TEST run
